<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


//  - bobot aspek_penilaian (patch)
// - 20 indikator_penilaian
// - 171 data_dukung
// Sumber data: DIGITAMA_20_INDIKATOR_PEMDI_Projection.xlsx (sheet
// INSTRUMEN EVAL PEMDI & EVIDENCE), sudah dibersihkan dari 2 bug sumber:
//   1) Indikator 8 level 4: bobot dinormalisasi (total 1.0 -> 0.5)
//   2) Indikator 19 level 3 item 1: teks lorem ipsum nyasar dibersihkan
class DigitamaMasterSeeder extends Seeder
{
    public function run(): void
    {
        // Bobot aspek (total = 1.0)
        $aspekBobot = [
            1 => 0.10,
            2 => 0.10,
            3 => 0.15,
            4 => 0.15,
            5 => 0.10,
            6 => 0.15,
            7 => 0.25,
        ];
        foreach ($aspekBobot as $nomorAspek => $bobot) {
            DB::table('aspek_penilaian')->where('nomor_aspek', $nomorAspek)->update(['bobot' => $bobot]);
        }

        //  Indikator Penilaian (20 baris) 
        $indikator = [
            ['id_indikator' => 1, 'id_aspek' => 1, 'nomor_indikator' => 1, 'kode_indikator' => 'IND-01', 'nama_indikator' => 'Tingkat Kematangan Tata Kelola Pemerintah Digital', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.05, 'status' => 'AKTIF'],
            ['id_indikator' => 2, 'id_aspek' => 1, 'nomor_indikator' => 2, 'kode_indikator' => 'IND-02', 'nama_indikator' => 'Tingkat Kematangan Manajemen Layanan Digital Pemerintah', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.05, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_aspek' => 2, 'nomor_indikator' => 3, 'kode_indikator' => 'IND-03', 'nama_indikator' => 'Tingkat Kematangan Sumber Daya Manusia Pemerintah Digital', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.05, 'status' => 'AKTIF'],
            ['id_indikator' => 4, 'id_aspek' => 2, 'nomor_indikator' => 4, 'kode_indikator' => 'IND-04', 'nama_indikator' => 'Tingkat Kematangan Kolaborasi Pemerintah Digital', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.05, 'status' => 'AKTIF'],
            ['id_indikator' => 5, 'id_aspek' => 3, 'nomor_indikator' => 5, 'kode_indikator' => 'IND-05', 'nama_indikator' => 'Tingkat Kematangan Tata Kelola Data (Indeks Satu Data Indonesia)', 'sumber_indikator' => 'EKSTERNAL', 'bobot' => 0.05, 'status' => 'AKTIF'],
            ['id_indikator' => 6, 'id_aspek' => 3, 'nomor_indikator' => 6, 'kode_indikator' => 'IND-06', 'nama_indikator' => 'Tingkat Kematangan Penyelenggaraan Informasi Geospasial (Indeks Simpul Jaringan Informasi Geospasial)', 'sumber_indikator' => 'EKSTERNAL', 'bobot' => 0.03, 'status' => 'AKTIF'],
            ['id_indikator' => 7, 'id_aspek' => 3, 'nomor_indikator' => 7, 'kode_indikator' => 'IND-07', 'nama_indikator' => 'Tingkat Kematangan Pembangunan Statisik (Indeks Pembangunan Statistik)', 'sumber_indikator' => 'EKSTERNAL', 'bobot' => 0.03, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_aspek' => 3, 'nomor_indikator' => 8, 'kode_indikator' => 'IND-08', 'nama_indikator' => 'Tingkat Kematangan Pelindungan Data Pribadi', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.04, 'status' => 'AKTIF'],
            ['id_indikator' => 9, 'id_aspek' => 4, 'nomor_indikator' => 9, 'kode_indikator' => 'IND-09', 'nama_indikator' => 'Tingkat Kematangan Pelaksanaan Audit Keamanan Pemerintah Digital dan Teknologi Pemerintah Digital', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.04, 'status' => 'AKTIF'],
            ['id_indikator' => 10, 'id_aspek' => 4, 'nomor_indikator' => 10, 'kode_indikator' => 'IND-10', 'nama_indikator' => 'Tingkat Kematangan Keamanan Siber (Instrumen Pengukuran Kematangan Keamanan Siber dan Sandi)', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.04, 'status' => 'AKTIF'],
            ['id_indikator' => 11, 'id_aspek' => 4, 'nomor_indikator' => 11, 'kode_indikator' => 'IND-11', 'nama_indikator' => 'Tingkat Kematangan Penerapan Kriptografi Nasional untuk Keamanan Data (IKASANDI)', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.03, 'status' => 'AKTIF'],
            ['id_indikator' => 12, 'id_aspek' => 4, 'nomor_indikator' => 12, 'kode_indikator' => 'IND-12', 'nama_indikator' => 'Tingkat Kematangan Kapabilitas Penanganan Insiden Siber (Instrumen Pengukuran Kematangan Keamanan Siber dan Sandi)', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.04, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_aspek' => 5, 'nomor_indikator' => 13, 'kode_indikator' => 'IND-13', 'nama_indikator' => 'Tingkat Kematangan Aplikasi Pemerintah Digital', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.05, 'status' => 'AKTIF'],
            ['id_indikator' => 14, 'id_aspek' => 5, 'nomor_indikator' => 14, 'kode_indikator' => 'IND-14', 'nama_indikator' => 'Tingkat Kematangan Infrastruktur Pemerintah Digital', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.05, 'status' => 'AKTIF'],
            ['id_indikator' => 15, 'id_aspek' => 6, 'nomor_indikator' => 15, 'kode_indikator' => 'IND-15', 'nama_indikator' => 'Keterpaduan Proses Bisnis Lintas Sektor', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.04, 'status' => 'AKTIF'],
            ['id_indikator' => 16, 'id_aspek' => 6, 'nomor_indikator' => 16, 'kode_indikator' => 'IND-16', 'nama_indikator' => 'Integrasi Aplikasi', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.04, 'status' => 'AKTIF'],
            ['id_indikator' => 17, 'id_aspek' => 6, 'nomor_indikator' => 17, 'kode_indikator' => 'IND-17', 'nama_indikator' => 'Portal Layanan Digital Pemerintah', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.04, 'status' => 'AKTIF'],
            ['id_indikator' => 18, 'id_aspek' => 6, 'nomor_indikator' => 18, 'kode_indikator' => 'IND-18', 'nama_indikator' => 'Interoperabilitas Data (Indeks Satu Data Indonesia)', 'sumber_indikator' => 'EKSTERNAL', 'bobot' => 0.03, 'status' => 'AKTIF'],
            ['id_indikator' => 19, 'id_aspek' => 7, 'nomor_indikator' => 19, 'kode_indikator' => 'IND-19', 'nama_indikator' => 'Fasilitas Dukungan Pengguna Layanan Digital Pemerintah', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.10, 'status' => 'AKTIF'],
            ['id_indikator' => 20, 'id_aspek' => 7, 'nomor_indikator' => 20, 'kode_indikator' => 'IND-20', 'nama_indikator' => 'Tingkat Kepuasan Pengguna Layanan Digital Pemerintah', 'sumber_indikator' => 'INTERNAL', 'bobot' => 0.15, 'status' => 'AKTIF'],
        ];
        foreach ($indikator as $row) {
            DB::table('indikator_penilaian')->updateOrInsert(['id_indikator' => $row['id_indikator']], $row);
        }

        // Data Dukung (171 baris, hanya utk 16 indikator INTERNAL) 
        $dataDukung = [
            ['id_indikator' => 1, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Rancangan dokumen perencanaan Instansi Pemerintah yang berisi substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah dalam tahap penyusunan', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Sebagian substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Bukti kegiatan konsolidasi kolaboratif Tim Koordinasi Pemerintah Digital dalam menyusun substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 2, 'nomor' => 3, 'nama_data_dukung' => 'Perencanaan dan Anggaran yang mendukung sebagian substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 2, 'nomor' => 4, 'nama_data_dukung' => 'Pengisian Arsitektur Pemerintah Digital pada sebagian Layanan Digital Pemerintah melalui SIAP Digital', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Dokumen seluruh substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 3, 'nomor' => 2, 'nama_data_dukung' => 'Bukti kegiatan konsolidasi kolaboratif Tim Koordinasi Pemerintah Digital dalam menyusun substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 3, 'nomor' => 3, 'nama_data_dukung' => 'Perencanaan dan Anggaran yang mendukung substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 3, 'nomor' => 4, 'nama_data_dukung' => 'Pengisian Arsitektur Pemerintah Digital pada seluruh Layanan Digital Pemerintah prioritas dan/atau Layanan Digital Pemerintah tematik melalui SIAP Digital', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Bukti reviu atas penerapan Tata Kelola Transformasi Digital Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 4, 'nomor' => 2, 'nama_data_dukung' => 'Arsitektur Pemerintah Digital yang selanjutnya menjadi referensi pembangunan/pengembangan Keterpaduan Layanan Digital di Lingkungan Pemerintah Daerah, terintegrasi dengan Layanan Digital Pemerintah Provinsi dan menjadi bagian Layanan Digital Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Bukti tindak lanjut reviu atas penerapan Tata Kelola Transformasi Digital Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 1, 'id_tingkat' => 5, 'nomor' => 2, 'nama_data_dukung' => 'Perubahan Substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 2, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Substansi sebagian Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 2, 'id_tingkat' => 1, 'nomor' => 2, 'nama_data_dukung' => 'Bukti Pelaksanaan Manajemen pada Layanan Digital Pemerintah sesuai dengan kebutuhan internal', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 2, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Substansi seluruh Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 2, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Bukti Pelaksanaan Manajemen pada sebagian Layanan Digital Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 2, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Bukti Pelaksanaan Manajemen Layanan Digital Pemerintah pada seluruh Layanan Digital Pemerintah sesuai Rencana Aksi Nasional Pemerintah Digital', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 2, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Laporan Reviu Penerapan Manajemen Layanan Digital Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 2, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Optimalisasi Manajemen Layanan Digital Pemerintah', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Peta Kompetensi untuk pelaksanaan Pemerintah Digital', 'bobot' => 0.1250, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 1, 'nomor' => 2, 'nama_data_dukung' => 'Bukti penggunaan aplikasi dasar dan sistem kerja digital internal', 'bobot' => 0.1250, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 1, 'nomor' => 3, 'nama_data_dukung' => 'Dokumentasi pelaksanaan komunitas belajar', 'bobot' => 0.1250, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 1, 'nomor' => 4, 'nama_data_dukung' => 'Laporan penggunaan microlearning internal (modul singkat, video e-learning sederhana)', 'bobot' => 0.1250, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Peta Kompetensi untuk pelaksanaan Pemerintah Digital', 'bobot' => 0.2000, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Laporan peningkatan kompetensi digital', 'bobot' => 0.2000, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 2, 'nomor' => 3, 'nama_data_dukung' => 'Dokumentasi pelaksanaan komunitas belajar (20% ASN)', 'bobot' => 0.2000, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 2, 'nomor' => 4, 'nama_data_dukung' => 'Laporan penggunaan pembelajaran digital nasional', 'bobot' => 0.2000, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 2, 'nomor' => 5, 'nama_data_dukung' => 'Laporan keikutsertaan pada forum internasional dalam meningkatkan kompetensi digital ASN', 'bobot' => 0.2000, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Peta Kompetensi Digital untuk pelaksanaan Pemerintah Digital', 'bobot' => 0.2000, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 3, 'nomor' => 2, 'nama_data_dukung' => 'Laporan peningkatan kompetensi digital', 'bobot' => 0.2000, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 3, 'nomor' => 3, 'nama_data_dukung' => 'Dokumentasi pelaksanaan komunitas belajar (50% ASN)', 'bobot' => 0.2000, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 3, 'nomor' => 4, 'nama_data_dukung' => 'Laporan Pemanfaatan AI dan Analisis Data (20% ASN)', 'bobot' => 0.2000, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 3, 'nomor' => 5, 'nama_data_dukung' => 'Laporan keikutsertaan pada forum internasional dalam meningkatkan kompetensi digital ASN (50% ASN)', 'bobot' => 0.2000, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Peta Kompetensi DIgital untuk pelaksanaan Pemerintah Digital', 'bobot' => 0.1250, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 4, 'nomor' => 2, 'nama_data_dukung' => 'Laporan peningkatan kompetensi digital', 'bobot' => 0.1250, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 4, 'nomor' => 3, 'nama_data_dukung' => 'Dokumentasi pelaksanaan komunitas belajar (75% ASN)', 'bobot' => 0.1250, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 4, 'nomor' => 4, 'nama_data_dukung' => 'Laporan pemanfaatan AI dan Analisis Data yang intensif (50% ASN)', 'bobot' => 0.1250, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Peta Kompetensi Digital untuk pelaksanaan Pemerintah Digital', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 5, 'nomor' => 2, 'nama_data_dukung' => 'Laporan peningkatan kompetensi digital', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 5, 'nomor' => 3, 'nama_data_dukung' => 'Dokumentasi pelaksanaan komunitas belajar (90% ASN)', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 5, 'nomor' => 4, 'nama_data_dukung' => 'Laporan pemanfaatan AI dan Analisi Data yang intensif (90% ASN)', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 5, 'nomor' => 5, 'nama_data_dukung' => 'Bukti keahlian digital (20% ASN)', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 3, 'id_tingkat' => 5, 'nomor' => 6, 'nama_data_dukung' => 'Laporan pemanfaatan teknologi terbaru', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 4, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Penetapan Tim Koordinasi Pemerintah Digital Instansi Pemerintah', 'bobot' => 0.1700, 'status' => 'AKTIF'],
            ['id_indikator' => 4, 'id_tingkat' => 1, 'nomor' => 2, 'nama_data_dukung' => 'Substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah dengan rincian rencana kolaborasi antar unit kerja/perangkat daerah dalam menerapkan Pemerintah Digital', 'bobot' => 0.1700, 'status' => 'AKTIF'],
            ['id_indikator' => 4, 'id_tingkat' => 1, 'nomor' => 3, 'nama_data_dukung' => 'Bukti Pelaksanaan Kolaborasi antar unit kerja/perangkat daerah dalam menerapkan Pemerintah Digital sesuai Substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 0.1700, 'status' => 'AKTIF'],
            ['id_indikator' => 4, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah dengan rincian rencana kolaborasi antar Instansi Pemerintah dalam menerapkan Pemerintah Digital', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 4, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Bukti Pelaksanaan Kolaborasi antar Instansi Pemerintah dalam menerapkan Pemerintah Digital sesuai Substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 4, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Bukti Pelaksanaan Kolaborasi perencanaan Instansi Pemerintah bersama dan tidak terbatas kepada akademisi, lembaga penelitian, pelaku usaha, industri, media, komunitas, dan organisasi masyarakat baik dalam negeri maupun luar negeri dalam menerapkan Pemerintah Digital sesuai Substansi Rencana Aksi Nasional Pemerintah Digital pada perencanaan Instansi Pemerintah', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 4, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Laporan Reviu kegiatan Kolaborasi Pemerintah Digital', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 4, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Optimalisasi Kolaborasi Pemerintah Digital', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Dokumentasi uraian Tata Kelola Pelindungan Data Pribadi', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 1, 'nomor' => 2, 'nama_data_dukung' => 'Dokumentasi uraian program awareness dan kompetensi Pelindungan Data Pribadi bagi pegawai', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 1, 'nomor' => 3, 'nama_data_dukung' => 'Dokumentasi uraian penunjukan Pejabat/Petugas PDP (DPO)', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 1, 'nomor' => 4, 'nama_data_dukung' => 'Dokumentasi uraian pelaksanaan mekanisme pemenuhan Hak Subjek data', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 1, 'nomor' => 5, 'nama_data_dukung' => 'Dokumentasi uraian pelaksanaan pemberitahuan pelindungan Data Pribadi', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 1, 'nomor' => 6, 'nama_data_dukung' => 'Dokumentasi  uraian pelaksanaan mekanisme pengamanan Data Pribadi', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 1, 'nomor' => 7, 'nama_data_dukung' => 'Dokumentasi uraian pelaksanaan mekanisme Pengelolaan Risiko atau Dampak Data Pribadi', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Dokumentasi Tata Kelola Pelindungan Data Pribadi secara menyeluruh', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Dokumentasi pelaksanaan program awareness dan kompetensi Pelindungan Data Pribadi bagi pegawai', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 2, 'nomor' => 3, 'nama_data_dukung' => 'Dokumen penunjukkan Pejabat/Petugas PDP (DPO)', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 2, 'nomor' => 4, 'nama_data_dukung' => 'Dokumentasi mekanisme pemenuhan Hak Subjek Data pada sebagian Layanan Digital Pemerintah', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 2, 'nomor' => 5, 'nama_data_dukung' => 'Dokumentasi pemberitahuan pelindungan Data Pribadi dan terpublikasi pada sebagian Layanan Digital Pemerintah', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 2, 'nomor' => 6, 'nama_data_dukung' => 'Dokumentasi mekanisme pengamanan Data Pribadi pada sebagian Layanan Digital Pemerintah', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 2, 'nomor' => 7, 'nama_data_dukung' => 'Dokumentasi mekanisme Pengelolaan Risiko atau Dampak Data Pribadi pada sebagian Layanan Digital Pemerintah', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Dokumentasi penerapan Tata Kelola Pelindungan Data Pribadi pada seluruh Layanan Digital Pemerintah', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 3, 'nomor' => 2, 'nama_data_dukung' => 'Dokumentasi pelaksanaan program awareness dan kompetensi Pelindungan Data Pribadi bagi pegawai secara berkala', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 3, 'nomor' => 3, 'nama_data_dukung' => 'Dokumentasi pelaksanaan tugas dan fungsi Pejabat/Petugas PDP (DPO)', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 3, 'nomor' => 4, 'nama_data_dukung' => 'Dokumentasi mekanisme pemenuhan Hak Subjek Data pada seluruh Layanan Digital Pemerintah', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 3, 'nomor' => 5, 'nama_data_dukung' => 'Dokumentasi pemberitahuan pelindungan Data Pribadi dan terpublikasi pada seluruh Layanan Digital Pemerintah', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 3, 'nomor' => 6, 'nama_data_dukung' => 'Dokumentasi mekanisme pengamanan Data Pribadi pada seluruh Layanan Digital', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 3, 'nomor' => 7, 'nama_data_dukung' => 'Dokumentasi mekanisme Pengelolaan Risiko atau Dampak Data Pribadi pada seluruh Layanan Digital Pemerintah', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Dokumentasi evaluasi Tata Kelola Pelindungan Data Pribadi', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 4, 'nomor' => 2, 'nama_data_dukung' => 'Dokumentasi evaluasi pada pelaksanaan program awareness dan kompetensi Pelindungan Data Pribadi bagi pegawai', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 4, 'nomor' => 3, 'nama_data_dukung' => 'Dokumentasi evaluasi pada pelaksanaan tugas dan fungsi Pejabat/Petugas PDP (DPO)', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 4, 'nomor' => 4, 'nama_data_dukung' => 'Dokumentasi evaluasi pada mekanisme pemenuhan Hak Subjek Data', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 4, 'nomor' => 5, 'nama_data_dukung' => 'Dokumentasi evaluasi pada substansi pelaksanaan publikasi pemberitahuan Data Pribadi', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 4, 'nomor' => 6, 'nama_data_dukung' => 'Dokumentasi evaluasi pada mekanisme pengamanan Data Pribadi', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 4, 'nomor' => 7, 'nama_data_dukung' => 'Dokumentasi evaluasi berkala pada Pengelolaan Risiko atau Dampak Data Pribadi pada seluruh Layanan Digital Pemerintah', 'bobot' => 0.0714, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Dokumentasi tindak lanjut hasil evaluasi Tata Kelola Pelindungan Data Pribadi', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 5, 'nomor' => 2, 'nama_data_dukung' => 'Dokumentasi tindak lanjut hasil evaluasi pada pelaksanaan program awareness dan kompetensi Pelindungan Data Pribadi bagi pegawai', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 5, 'nomor' => 3, 'nama_data_dukung' => 'Dokumentasi tindak lanjut hasil evaluasi pada pelaksanaan tugas dan fungsi Pejabat/Petugas PDP (DPO)', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 5, 'nomor' => 4, 'nama_data_dukung' => 'Dokumentasi tindak lanjut hasil evaluasi pada mekanisme pemenuhan Hak Subjek Data', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 5, 'nomor' => 5, 'nama_data_dukung' => 'Dokumentasi hasil evaluasi pada substansi pelaksanaan publikasi pemberitahuan Data Pribadi', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 5, 'nomor' => 6, 'nama_data_dukung' => 'Dokumentasi tindak lanjut hasil evaluasi pada mekanisme pengamanan Data Pribadi', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 8, 'id_tingkat' => 5, 'nomor' => 7, 'nama_data_dukung' => 'Dokumentasi tindak lanjut hasil evaluasi berkala pada Pengelolaan Risiko atau Dampak Data Pribadi', 'bobot' => 0.1429, 'status' => 'AKTIF'],
            ['id_indikator' => 9, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Penetapan Tim Audit yang ditetapkan oleh Koordinator Pemerintah Digital di setiap Instansi Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 9, 'id_tingkat' => 1, 'nomor' => 2, 'nama_data_dukung' => 'Dokumen Perencanaan Audit Instansi Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 9, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Laporan Hasil Audit Internal Keamanan Pemerintah Digital dan Teknologi Pemerintah Digital Internal', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 9, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Laporan Hasil Tindak Lanjut Audit Keamanan Pemerintah Digital dan Teknologi Pemerintah Digital', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 9, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Laporan Hasil Audit Eksternal Keamanan Pemerintah Digital dan Teknologi Pemerintah Digital', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 9, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Laporan Hasil Tindak Lanjut Audit Eksternal Keamanan Pemerintah Digital dan Teknologi Pemerintah Digital', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 10, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Nilai IKASANDI pada area Keamanan Siber 0 <= IKASANDI < 1,50', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 10, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Dokumentasi Identifikasi Infrastruktur Informasi Vital', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 10, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Nilai IKASANDI pada area Keamanan Siber 1,50 <= IKASANDI < 2,50', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 10, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Nilai IKASANDI pada area Keamanan Siber 2,50 <= IKASANDI < 3,50', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 10, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Instrumen IKASANDI pada area Keamanan Siber 3,50 <= IKASANDI < 4,00', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 10, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Instrumen IKASANDI pada area Keamanan Siber 4,00 <= IKASANDI <= 5,00', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 11, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Identifikasi aset yang dilakukan enkripsi Laporan pelaksanaan penerapan teknologi kriptografi', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 11, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Laporan pelaksanaan penerapan teknologi kriptografi', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 11, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Laporan pelaksanaan penerapan teknologi kriptografi', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 11, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Laporan evaluasi penerapan teknologi kriptografi', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 11, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Laporan tindak lanjut hasil evaluasi penerapan teknologi kriptografi', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 11, 'id_tingkat' => 5, 'nomor' => 2, 'nama_data_dukung' => 'Nilai IKASANDI pada Area Kematangan Persandian 4,00 <= IKASANDI <= 5,00', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 12, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Dokumentasi pelaksanaan penanganan insiden', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 12, 'id_tingkat' => 1, 'nomor' => 2, 'nama_data_dukung' => 'Nilai IKASANDI pada area Penanganan Insiden Siber 0 <= IKASANDI < 1,50 (* bukan hasil verifikasi oleh lembaga yang menyelenggarakan tugas pemerintahan di bidang siber dan sandi)', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 12, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Penetapan TTIS', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 12, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Nilai IKASANDI pada area Penanganan Insiden Siber 1,50 <= IKASANDI < 2,50 (* bukan hasil verifikasi oleh lembaga yang menyelenggarakan tugas pemerintahan di bidang siber dan sandi)', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 12, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Instrumen IKASANDI area Penanganan Insiden Siber 2,50 <= IKASANDI < 3,50', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 12, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Instrumen IKASANDI area Penanganan Insiden Siber 3,50 <= IKASANDI < 4,00', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 12, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Instrumen IKASANDI area Penanganan Insiden Siber 4,00 <= IKASANDI <= 5,00', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Bukti Pelaksanaan Pengembangan Aplikasi', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 1, 'nomor' => 2, 'nama_data_dukung' => 'Substansi Rencana Aksi Pemerintah Digital pada Perencanaan Instansi Pemerintah', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 1, 'nomor' => 3, 'nama_data_dukung' => 'Aplikasi Pemerintah Digital pada Arsitektur Teknologi Pemerintah Digital dari SIAP Digital', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Dokumentasi pembangunan/pengembangan aplikasi Pemerintah Digital', 'bobot' => 0.3333, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Substansi Rencana Aksi Pemerintah Digital pada Perencanaan Instansi Pemerintah', 'bobot' => 0.3333, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 2, 'nomor' => 3, 'nama_data_dukung' => 'Laporan hasil reviu Unit Pengelola Layanan Digital', 'bobot' => 0.3333, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Dokumentasi pengembangan/pembangunan aplikasi Pemerintah Digital', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 3, 'nomor' => 2, 'nama_data_dukung' => 'Laporan hasil reviu Unit Pengelola Layanan Digital', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 3, 'nomor' => 3, 'nama_data_dukung' => 'Laporan hasil terminasi aplikasi Pemerintah Digital', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 3, 'nomor' => 4, 'nama_data_dukung' => 'Repositori aplikasi Pemerintah Digital', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Laporan reviu pelaksanaan pembangunan/pengembangan aplikasi', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 13, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Perbaikan pelaksanaan pembangunan/pengembangan aplikasi berdasarkan hasil laporan reviu', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 14, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Dasbor Ekosistem Pusat Data yang dimanfaatkan oleh Instansi Pemerintah', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 14, 'id_tingkat' => 1, 'nomor' => 2, 'nama_data_dukung' => 'Infrastruktur Digital pada Arsitektur Teknologi Pemerintah Digital dari SIAP Digital', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 14, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Laporan pemantauan pemanfaatan infrastruktur Pemerintah Digital pada sebagian Layanan Digital Instansi Pemerintah yang berisikan matriks pemanfaatan infrastruktur Pemerintah Digital', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 14, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Laporan pemantauan pemanfaatan infrastruktur Pemerintah Digital pada seluruh Layanan Digital Instansi Pemerintah yang berisikan matriks pemanfaatan infrastruktur Pemerintah Digital', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 14, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Laporan Reviu infrastruktur Pemerintah Digital', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 14, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Laporan tindak lanjut infrastruktur Pemerintah Digital', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 15, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Proses Bisnis Pemerintah Digital untuk mendukung Layanan Digital pada Arsitektur Pemerintah Digital dari SIAP Digital', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 15, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Pemetaan proses bisnis Pemerintah Digital untuk mendukung Layanan Digital dari SIAP Digital', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 15, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Proses bisnis to-be yang mendukung keterpaduan Layanan Digital Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 15, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Pemetaan proses bisnis Pemerintah Digital untuk mendukung Layanan Digital dari SIAP Digital di seluruh Layanan Digital Pemerintah prioritas dan/atau Layanan Digital Pemerintah tematik', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 15, 'id_tingkat' => 3, 'nomor' => 2, 'nama_data_dukung' => 'Proses bisnis to-be yang mendukung keterpaduan Layanan Digital Pemerintah di seluruh Layanan Digital Pemerintah prioritas dan/atau Layanan Digital Pemerintah tematik', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 15, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Reviu pelaksanaan keterpaduan proses bisnis Pemerintah Digital untuk mendukung Layanan Digital Pemerintah Instansi Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 15, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Tindak lanjut hasil reviu pelaksanaan keterpaduan proses bisnis Layanan Digital Pemerintah Instansi Pemerintah', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 16, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Laporan Pelaksanaan Integrasi Aplikasi yang berisikan', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 16, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Pemetaan Integrasi Aplikasi sesuai Rencana Aksi Pemerintah digital yang terdapat pada Perencanaan Instansi Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 16, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Laporan pelaksanaan integrasi aplikasi pada sebagian layanan yang berisikan uraian pelaksanaan dan matriks pemantauan Integrasi Aplikasi', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 16, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Laporan pelaksanaan integrasi aplikasi pada seluruh layanan yang berisikan uraian pelaksanaan dan matriks pemantauan Integrasi Aplikasi', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 16, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Matriks pemantauan reviu pelaksanaan Integrasi Aplikasi', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 16, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Matriks pemantauan hasil tindak lanjut Integrasi Aplikasi', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 17, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Portal Layanan Digital Pemerintah pada Instansi Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 17, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Rencana Layanan Digital yang akan di padukan pada portal sesuai perencanaan yang memuat substansi rencana aksi nasional Pemerintah Digital', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 17, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Portal Layanan Digital Pemerintah pada Instansi Pemerintah pada sebagian Layanan Digital Pemerintah berbasis siklus hidup', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 17, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Portal Layanan Digital Pemerintah pada Instansi Pemerintah pada seluruh Layanan Digital Pemerintah berbasis siklus hidup', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 17, 'id_tingkat' => 3, 'nomor' => 2, 'nama_data_dukung' => 'Dasbor matriks pemantauan data Pemanfaatan Portal Layanan Digital Pemerintah Nasional', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 17, 'id_tingkat' => 3, 'nomor' => 3, 'nama_data_dukung' => 'Persentase pemanfaatan Portal Layanan Digital Pemerintah Nasional lebih dari 50% dari populasi pengguna', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 17, 'id_tingkat' => 3, 'nomor' => 4, 'nama_data_dukung' => 'Portal Layanan Digital Pemerintah pada Instansi Pemerintah menggunakan identitas digital yang diterbitkan oleh penyedia identitas digital', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 17, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Matriks pemantauan reviu pelaksanaan Integrasi Aplikasi', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 17, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Matriks pemantauan hasil tindak lanjut Integrasi Aplikasi', 'bobot' => 1.0000, 'status' => 'AKTIF'],
            ['id_indikator' => 19, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Dasbor Fasilitas Dukungan Pengguna Layanan Digital Pemerintah', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 19, 'id_tingkat' => 1, 'nomor' => 2, 'nama_data_dukung' => 'Dasbor Pemantauan pemenuhan SLA', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 19, 'id_tingkat' => 1, 'nomor' => 3, 'nama_data_dukung' => 'Dasbor pemantauan proses dan SLA setiap tahapan layanan per-pengguna', 'bobot' => 0.1667, 'status' => 'AKTIF'],
            ['id_indikator' => 19, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Dasbor Fasilitas Dukungan Pengguna Layanan Digital Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 19, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Pemenuhan Standar Layanan Digital 90% (SLA lebih dari 90%)', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 19, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Sapiente est hic est.Dasbor Fasilitas Dukungan Pengguna Layanan Digital Pemerintah', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 19, 'id_tingkat' => 3, 'nomor' => 2, 'nama_data_dukung' => 'Pemenuhan Standar Layanan Digital 99% (SLA lebih dari 99%)', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 19, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Laporan Pelaksanaan Evaluasi Kepatuhan SLA dan Fasilitas Dukungan Pengguna', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 19, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Tindak Lanjut matriks pemantauan data pelaksanaan Fasilitas Dukungan Pengguna', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 19, 'id_tingkat' => 5, 'nomor' => 2, 'nama_data_dukung' => 'Pemenuhan Standar Layanan Digital 99,9% (SLA 99,9%)', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 20, 'id_tingkat' => 1, 'nomor' => 1, 'nama_data_dukung' => 'Hasil kepuasan pengguna layanan', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 20, 'id_tingkat' => 2, 'nomor' => 1, 'nama_data_dukung' => 'Bukti pelibatan masyarakat dalam diskusi hasil survei', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 20, 'id_tingkat' => 2, 'nomor' => 2, 'nama_data_dukung' => 'Hasil kepuasan pengguna layanan', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 20, 'id_tingkat' => 3, 'nomor' => 1, 'nama_data_dukung' => 'Bukti pelibatan masyarakat dalam diskusi hasil survei', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 20, 'id_tingkat' => 3, 'nomor' => 2, 'nama_data_dukung' => 'Hasil kepuasan pengguna layanan', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 20, 'id_tingkat' => 4, 'nomor' => 1, 'nama_data_dukung' => 'Log Perubahan', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 20, 'id_tingkat' => 4, 'nomor' => 2, 'nama_data_dukung' => 'Hasil kepuasan pengguna layanan', 'bobot' => 0.2500, 'status' => 'AKTIF'],
            ['id_indikator' => 20, 'id_tingkat' => 5, 'nomor' => 1, 'nama_data_dukung' => 'Log Perubahan', 'bobot' => 0.5000, 'status' => 'AKTIF'],
            ['id_indikator' => 20, 'id_tingkat' => 5, 'nomor' => 2, 'nama_data_dukung' => 'Hasil kepuasan pengguna layanan', 'bobot' => 0.5000, 'status' => 'AKTIF'],
        ];
        foreach ($dataDukung as $row) {
            DB::table('data_dukung')->updateOrInsert(
                ['id_indikator' => $row['id_indikator'], 'id_tingkat' => $row['id_tingkat'], 'nomor' => $row['nomor']],
                $row
            );
        }
    }
}